### ISSUE TITLE
bug with Jekyll 3.3.0

### ISSUE THREAD

**Issue by alessiofx** [jekyll/jekyll-archives#79] opened 2016-10-15 20:40 UTC
when I launch Jekyll s

jekyll 3.3.0 | Error:  undefined method `extname' for #<Jekyll::Archives::Archive:0x007fc58a9fbda0>

why??

**Comment by pathawks** [comment] 2016-10-15 20:49
Fixed in current master. Closing as a duplicate of #76

**Closed by pathawks** 2016-10-15 20:49 UTC
