### ISSUE TITLE
Loop through site.posts?

### ISSUE THREAD

**Issue by chrisfinazzo** [jekyll/jekyll-archives#134] opened 2019-04-02 18:30 UTC
For the examples listed on the [layouts](https://github.com/jekyll/jekyll-archives/blob/master/docs/layouts.md) page, shouldn't the loop be `{% for post in page.posts %}`? As written, when I try this on my own site nothing renders, but if I use `site.posts` an archive appears.

Jekyll 3.8.5
Jekyll Archives 2.2.1
Ruby 2.5.0

**Comment by ashmaroli** [comment] 2019-04-03 02:14
From the source-code, it looks like `page.posts` is the correct accessor:
https://github.com/jekyll/jekyll-archives/blob/44e357429136e8b70d31537814d1532f107b8932/lib/jekyll-archives/archive.rb#L26-L29

Do you have a sample test-repository that I can clone and reproduce this..?

**Comment by chrisfinazzo** [comment] 2019-04-03 04:05
I don't have a testing repo, but I can reproduce my setup here. While this currently _works_, I'm wondering if there's a simpler way to go about it. For the record, `page.posts` is correct, my bad. 

```
    jekyll-archives:
      enabled: year
      layout: archive
      permalinks:
        year: '/archive/:year/'
```

    ---
    layout: default
    ---
    
    {% for post in site.posts  %}
            {% capture this_year %}{{ post.date | date: "%Y" }}{% endcapture %}
            {% capture next_year %}{{ post.previous.date | date: "%Y" }}{% endcapture %}

        {% if forloop.first %}
        <h2 id="{{ this_year }}-ref">{{this_year}}</h2>
        <ul>
        {% endif %}

        <li><a href="{{ post.url }}">{{ post.title }}</a></li>

        {% if forloop.last %}
        </ul>
        {% else %}
            {% if this_year != next_year %}
            </ul>
            <h2 id="{{ next_year }}-ref">{{next_year}}</h2>
            <ul>
            {% endif %}
        {% endif %}
    {% endfor %}

**Comment by ashmaroli** [comment] 2019-04-03 04:17
What is your use-case @chrisfinazzo ?
The above Liquid code is quite a nasty hack! It considerably lowers you site's maintainability score. 

I'm closing this since this does not look like a bug-report to me.
You may find assistance at Jekyll Talk..

**Closed by ashmaroli** 2019-04-03 04:17 UTC
Labels: support
